import { Response } from 'express';
import { pool } from '../utils/db.js';
import { AuthRequest } from '../middleware/auth.js';
import { assertModulePermission, ModulePermissionError } from '../permissions/index.js';
import { z } from 'zod';

const ticketSchema = z.object({
  contact_name: z.string().min(1),
  contact_email: z.string().email(),
  contact_phone: z.string().optional().nullable(),
  subject: z.string().min(1),
  description: z.string().min(1),
  category_id: z.string().uuid().optional().nullable(),
  priority: z.enum(['low', 'normal', 'high', 'urgent']).optional(),
  status: z.enum(['new', 'open', 'pending', 'waiting_customer', 'in_progress', 'resolved', 'closed', 'cancelled']).optional(),
  channel: z.enum(['portal', 'email', 'whatsapp', 'internal']).optional(),
  client_id: z.string().uuid().optional().nullable(),
  team_id: z.string().uuid().optional().nullable(),
  assignee_id: z.string().uuid().optional().nullable(),
  tags: z.array(z.string()).optional(),
  custom_fields: z.any().optional(),
});

// Get tickets with filters
export async function getTickets(req: AuthRequest, res: Response): Promise<void> {
  try {
    const tenantId = req.tenantId ?? null;
    if (!tenantId) {
      res.json([]);
      return;
    }
    const { status, priority, category_id, search } = req.query;

    let query = `SELECT t.* FROM tickets t
       INNER JOIN users u ON u.id = t.user_id AND u.tenant_id = $1
       WHERE 1=1`;
    const params: any[] = [tenantId];
    let paramIndex = 2;

    if (status && status !== 'all') {
      query += ` AND t.status = $${paramIndex}`;
      params.push(status);
      paramIndex++;
    }

    if (priority) {
      query += ` AND t.priority = $${paramIndex}`;
      params.push(priority);
      paramIndex++;
    }

    if (category_id) {
      query += ` AND t.category_id = $${paramIndex}`;
      params.push(category_id);
      paramIndex++;
    }

    if (search) {
      query += ` AND (t.subject ILIKE $${paramIndex} OR t.ticket_number ILIKE $${paramIndex} OR t.contact_name ILIKE $${paramIndex})`;
      params.push(`%${search}%`);
      paramIndex++;
    }

    query += ' ORDER BY t.created_at DESC';

    const result = await pool.query(query, params);
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching tickets:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get ticket by ID
export async function getTicketById(req: AuthRequest, res: Response): Promise<void> {
  try {
    const userId = req.userId!;
    const { id } = req.params;

    const result = await pool.query(
      `SELECT t.* FROM tickets t
       INNER JOIN users u ON u.id = t.user_id AND u.tenant_id = (SELECT tenant_id FROM users WHERE id = $2)
       WHERE t.id = $1`,
      [id, userId]
    );

    if (result.rows.length === 0) {
      res.status(404).json({ error: 'Ticket not found' });
      return;
    }

    res.json(result.rows[0]);
  } catch (error) {
    console.error('Error fetching ticket:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Create ticket
export async function createTicket(req: AuthRequest, res: Response): Promise<void> {
  try {
    const userId = req.userId!;
    const ticketData = ticketSchema.parse(req.body);

    await assertModulePermission(userId, 'tickets', 'create', undefined, req);

    // Generate ticket number (will be auto-generated by trigger, but we can set it explicitly)
    const ticketNumber = `TICKET-${Date.now()}-${Math.random().toString(36).substr(2, 6).toUpperCase()}`;

    const result = await pool.query(
      `INSERT INTO tickets (
        ticket_number, user_id, contact_name, contact_email, contact_phone,
        subject, description, category_id, priority, status, channel,
        client_id, team_id, assignee_id, tags, custom_fields
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
      RETURNING *`,
      [
        ticketNumber, userId, ticketData.contact_name, ticketData.contact_email,
        ticketData.contact_phone || null, ticketData.subject, ticketData.description,
        ticketData.category_id || null, ticketData.priority || 'normal',
        ticketData.status || 'new', ticketData.channel || 'internal',
        ticketData.client_id || null, ticketData.team_id || null,
        ticketData.assignee_id || null, ticketData.tags ? JSON.stringify(ticketData.tags) : '[]',
        ticketData.custom_fields ? JSON.stringify(ticketData.custom_fields) : '{}'
      ]
    );

    res.status(201).json(result.rows[0]);
  } catch (error) {
    if (error instanceof ModulePermissionError) {
      res.status(error.statusCode).json({ error: error.message });
      return;
    }
    if (error instanceof z.ZodError) {
      res.status(400).json({ error: 'Validation error', details: error.errors });
      return;
    }
    console.error('Error creating ticket:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Update ticket
export async function updateTicket(req: AuthRequest, res: Response): Promise<void> {
  try {
    const userId = req.userId!;
    const { id } = req.params;
    const ticketData = ticketSchema.partial().parse(req.body);

    const existing = await pool.query<{ user_id: string; assignee_id: string | null }>(
      `SELECT user_id, assignee_id FROM tickets t
       INNER JOIN users u ON u.id = t.user_id AND u.tenant_id = (SELECT tenant_id FROM users WHERE id = $2)
       WHERE t.id = $1`,
      [id, userId]
    );
    if (existing.rows.length === 0) {
      res.status(404).json({ error: 'Ticket not found' });
      return;
    }
    const row = existing.rows[0];
    await assertModulePermission(userId, 'tickets', 'edit', {
      ownerId: row.user_id,
      assigneeId: row.assignee_id,
    }, req);

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    Object.entries(ticketData).forEach(([key, value]) => {
      if (value !== undefined) {
        if (key === 'tags' || key === 'custom_fields') {
          updates.push(`${key} = $${paramIndex}`);
          values.push(JSON.stringify(value));
        } else {
          updates.push(`${key} = $${paramIndex}`);
          values.push(value);
        }
        paramIndex++;
      }
    });

    if (updates.length === 0) {
      res.status(400).json({ error: 'No fields to update' });
      return;
    }

    values.push(id, userId);
    const result = await pool.query(
      `UPDATE tickets 
       SET ${updates.join(', ')}, updated_at = now()
       WHERE id = $${paramIndex} AND user_id IN (SELECT id FROM users WHERE tenant_id = (SELECT tenant_id FROM users WHERE id = $${paramIndex + 1}))
       RETURNING *`,
      values
    );

    if (result.rows.length === 0) {
      res.status(404).json({ error: 'Ticket not found' });
      return;
    }

    res.json(result.rows[0]);
  } catch (error) {
    if (error instanceof ModulePermissionError) {
      res.status(error.statusCode).json({ error: error.message });
      return;
    }
    if (error instanceof z.ZodError) {
      res.status(400).json({ error: 'Validation error', details: error.errors });
      return;
    }
    console.error('Error updating ticket:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Delete ticket
export async function deleteTicket(req: AuthRequest, res: Response): Promise<void> {
  try {
    const userId = req.userId!;
    const { id } = req.params;

    const existing = await pool.query<{ user_id: string; assignee_id: string | null }>(
      `SELECT user_id, assignee_id FROM tickets t
       INNER JOIN users u ON u.id = t.user_id AND u.tenant_id = (SELECT tenant_id FROM users WHERE id = $2)
       WHERE t.id = $1`,
      [id, userId]
    );
    if (existing.rows.length === 0) {
      res.status(404).json({ error: 'Ticket not found' });
      return;
    }
    const row = existing.rows[0];
    await assertModulePermission(userId, 'tickets', 'delete', {
      ownerId: row.user_id,
      assigneeId: row.assignee_id,
    }, req);

    const result = await pool.query(
      `DELETE FROM tickets WHERE id = $1 AND user_id IN (SELECT id FROM users WHERE tenant_id = (SELECT tenant_id FROM users WHERE id = $2)) RETURNING id`,
      [id, userId]
    );

    if (result.rows.length === 0) {
      res.status(404).json({ error: 'Ticket not found' });
      return;
    }

    res.json({ message: 'Ticket deleted successfully' });
  } catch (error) {
    if (error instanceof ModulePermissionError) {
      res.status(error.statusCode).json({ error: error.message });
      return;
    }
    console.error('Error deleting ticket:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

