/**
 * Eventos de webhook do Asaas (tipados para evitar strings soltas).
 */
export const ASAAS_EVENT = {
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_UPDATED: 'PAYMENT_UPDATED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_OVERDUE: 'PAYMENT_OVERDUE',
  PAYMENT_DELETED: 'PAYMENT_DELETED',
  PAYMENT_RESTORED: 'PAYMENT_RESTORED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_RECEIVED_IN_CASH_UNDONE: 'PAYMENT_RECEIVED_IN_CASH_UNDONE',
  PAYMENT_CHARGEBACK_REQUESTED: 'PAYMENT_CHARGEBACK_REQUESTED',
  PAYMENT_CHARGEBACK_DISPUTE: 'PAYMENT_CHARGEBACK_DISPUTE',
  PAYMENT_AWAITING_CHARGEBACK_REVERSAL: 'PAYMENT_AWAITING_CHARGEBACK_REVERSAL',
  PAYMENT_DUNNING_RECEIVED: 'PAYMENT_DUNNING_RECEIVED',
  PAYMENT_DUNNING_REQUESTED: 'PAYMENT_DUNNING_REQUESTED',
  PAYMENT_BANK_SLIP_VIEWED: 'PAYMENT_BANK_SLIP_VIEWED',
  PAYMENT_CHECKOUT_VIEWED: 'PAYMENT_CHECKOUT_VIEWED',
} as const;

/** Sprint 10 — Pix Automático (não passam pelo path payment_id). */
export const ASAAS_PIX_AUTOMATIC_EVENT = {
  AUTHORIZATION_CREATED: 'PIX_AUTOMATIC_RECURRING_AUTHORIZATION_CREATED',
  AUTHORIZATION_ACTIVATED: 'PIX_AUTOMATIC_RECURRING_AUTHORIZATION_ACTIVATED',
  AUTHORIZATION_CANCELLED: 'PIX_AUTOMATIC_RECURRING_AUTHORIZATION_CANCELLED',
  AUTHORIZATION_EXPIRED: 'PIX_AUTOMATIC_RECURRING_AUTHORIZATION_EXPIRED',
  AUTHORIZATION_REFUSED: 'PIX_AUTOMATIC_RECURRING_AUTHORIZATION_REFUSED',
  INSTRUCTION_CREATED: 'PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_CREATED',
  INSTRUCTION_SCHEDULED: 'PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_SCHEDULED',
  INSTRUCTION_REFUSED: 'PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_REFUSED',
  INSTRUCTION_CANCELLED: 'PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_CANCELLED',
} as const;

export type AsaasEventType = (typeof ASAAS_EVENT)[keyof typeof ASAAS_EVENT];
export type AsaasPixAutomaticEventType =
  (typeof ASAAS_PIX_AUTOMATIC_EVENT)[keyof typeof ASAAS_PIX_AUTOMATIC_EVENT];

export function isAsaasPaymentEvent(value: string): value is AsaasEventType {
  return Object.values(ASAAS_EVENT).includes(value as AsaasEventType);
}

export function isAsaasPixAutomaticEvent(value: string): value is AsaasPixAutomaticEventType {
  return Object.values(ASAAS_PIX_AUTOMATIC_EVENT).includes(value as AsaasPixAutomaticEventType);
}
