// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meoatixglqaxnzzovuez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lb2F0aXhnbHFheG56em92dWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzkyNjYsImV4cCI6MjA2MzI1NTI2Nn0.ABOeTz4KYfbvpjosFcfmN2wgNWWIlYcJRZzEpk53WTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);